'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Eye, EyeOff, Info, ShoppingBag } from 'lucide-react'
import { Button } from '@/components/ui/button'

export function AuthScreen({ mode }: { mode: 'login' | 'register' }) {
  const [visible, setVisible] = useState(false)
  const [message, setMessage] = useState('')
  const register = mode === 'register'
  return <main className="auth-page"><section className="auth-art"><Link className="brand" href="/"><span className="brand-bag"><ShoppingBag size={24} /></span>daily<span>mart</span><span className="brand-dot">.</span></Link><div className="auth-art-copy"><h2>Your everyday.<br />A little better.</h2><p>Good finds. Fresh favourites. All in one happy place.</p></div><img src="/images/fresh-market.png" alt="A canvas tote filled with fresh produce and daily essentials" /></section><section className="auth-main"><Link className="back-link" href="/"><ArrowLeft size={14} /> Back to the store</Link><span className="eyebrow">A LITTLE MORE YOU</span><h1>{register ? 'Make yourself at home.' : 'Hello again, happy shopper.'}</h1><p className="auth-subtitle">{register ? 'Create your account for an easier everyday.' : 'Log in to find your favourites, all in one place.'}</p><div className="notice"><Info size={17} /><span>Account preview only. Authentication is not connected. Do not enter a real password; no account will be created.</span></div><form className="stack-form" onSubmit={event => { event.preventDefault(); setMessage(register ? 'Registration is unavailable until secure authentication is connected. No account was created or details saved.' : 'Login is unavailable until secure authentication is connected. You can continue exploring as a guest.') }}>{register && <label htmlFor="name">Full name<input id="name" name="name" placeholder="Your name" autoComplete="name" maxLength={100} required /></label>}<label htmlFor="email">Email address<input id="email" name="email" type="email" placeholder="you@example.com" autoComplete="email" required maxLength={254} /></label><label htmlFor="password">Password<div className="password-input"><input id="password" name="password" type={visible ? 'text' : 'password'} placeholder={register ? 'At least 8 characters' : 'Your password'} autoComplete={register ? 'new-password' : 'current-password'} minLength={8} maxLength={128} required /><button type="button" aria-label={visible ? 'Hide password' : 'Show password'} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label><Button type="submit" size="lg">{register ? 'Create account' : 'Log in'} <ArrowRight data-icon="inline-end" /></Button>{message && <p className="auth-status" role="status">{message}</p>}</form><p className="auth-footer">{register ? 'Already part of the neighbourhood? ' : 'New around here? '}<Link href={register ? '/login' : '/register'}>{register ? 'Log in' : 'Create an account'}</Link></p><p className="fine-print" style={{ marginTop: 24 }}>No account needed to explore this demo store.</p></section></main>
}
