'use client'

import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, Grid2X2, Heart, MapPin, Search, ShoppingBag, SlidersHorizontal, Sparkles, Tag, Truck, UserRound, X } from 'lucide-react'
import { categories, demoAddresses, products, money, type Address, type Cart, type Product } from '@/lib/catalog'
import { Hero, Categories, BottomSections } from '@/components/store-sections'
import { ProductCard } from '@/components/product-card'
import { AccountPanel, AddressPanel, CartPanel, HelpPanel, ProductDetail, StoreModal } from '@/components/store-panels'
import { cn } from '@/lib/utils'

type Panel = 'cart' | 'address' | 'help' | 'account' | 'product' | null
export function Storefront() {
  const [category, setCategory] = useState('All')
  const [query, setQuery] = useState('')
  const [cart, setCart] = useState<Cart>({})
  const [saved, setSaved] = useState<string[]>([])
  const [savedOnly, setSavedOnly] = useState(false)
  const [dealsOnly, setDealsOnly] = useState(false)
  const [sort, setSort] = useState('recommended')
  const [panel, setPanel] = useState<Panel>(null)
  const [viewed, setViewed] = useState<Product | null>(null)
  const [addresses, setAddresses] = useState<Address[]>(demoAddresses)
  const [addressIndex, setAddressIndex] = useState(0)
  const [addressReturn, setAddressReturn] = useState<Panel>(null)
  const [notice, setNotice] = useState('')
  const totalCount = Object.values(cart).reduce((a, b) => a + b, 0)
  const total = products.reduce((sum, product) => sum + product.price * (cart[product.id] || 0), 0)
  const address = addresses[addressIndex]
  const shop = (next: string) => { setCategory(next); setSavedOnly(false); setDealsOnly(false); setQuery(''); setPanel(null); document.getElementById('products')?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
  const update = (id: string, delta: number) => { setCart(current => ({ ...current, [id]: Math.max(0, Math.min(10, (current[id] || 0) + delta)) })); if (delta > 0) setNotice('Added to your bag. A good little find!') }
  const filtered = products.filter(product => (category === 'All' || product.category === category) && (!savedOnly || saved.includes(product.id)) && (!dealsOnly || (1 - product.price / product.original) >= .25) && `${product.name} ${product.category}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'price-low' ? a.price - b.price : sort === 'price-high' ? b.price - a.price : sort === 'rating' ? Number(b.rating) - Number(a.rating) : 0)
  const title = panel === 'cart' ? `Your shopping bag (${totalCount})` : panel === 'address' ? 'Where should we deliver?' : panel === 'help' ? 'Meet your Daily assistant' : panel === 'product' ? viewed?.name || 'Product details' : 'Hello, happy shopper.'
  return <div className="storefront">
    <div className="announcement"><div className="page-container"><span><Truck size={14} /> A little convenience. A lot of happiness.</span><span>Everyday finds, all in one place <span className="announcement-dot">·</span> Made for your everyday</span></div></div>
    <header className="site-header"><div className="page-container header-main"><a className="brand" href="/" aria-label="Dailymart home"><span className="brand-bag"><ShoppingBag size={24} strokeWidth={1.8} /></span>daily<span>mart</span><span className="brand-dot">.</span></a><button className="location-button" onClick={() => { setAddressReturn(null); setPanel('address') }}><MapPin size={20} /><span><small>Deliver to</small><strong>{address.city} {address.pin} <ChevronDown size={12} /></strong></span></button><label className="search-box"><Search size={19} /><input aria-label="Search products" placeholder="Search for a little bit of everything…" value={query} onChange={event => { setQuery(event.target.value); setCategory('All'); setSavedOnly(false); setDealsOnly(false) }} />{query ? <button aria-label="Clear search" onClick={() => setQuery('')}><X size={15} /></button> : <span className="search-shortcut">Find your everyday</span>}</label><div className="header-actions"><button className="header-account" aria-label="Account" onClick={() => setPanel('account')}><UserRound size={21} /><span>Account</span></button><button className="header-wishlist" aria-label={`Show saved items (${saved.length})`} onClick={() => { setSavedOnly(!savedOnly); setCategory('All'); setQuery(''); setDealsOnly(false); document.getElementById('products')?.scrollIntoView({ behavior: 'smooth' }) }}><Heart size={21} fill={savedOnly ? 'currentColor' : 'none'} />{saved.length > 0 && <span className="small-count">{saved.length}</span>}</button><button className="cart-button" aria-label={`My bag, ${totalCount} items`} onClick={() => setPanel('cart')}><ShoppingBag size={18} /><span>My bag</span><b>{totalCount}</b></button></div></div></header>
    <nav className="category-nav" aria-label="Shop categories"><div className="page-container nav-inner"><button className={cn('all-categories', category === 'All' && 'active')} onClick={() => shop('All')}><Grid2X2 size={16} /> All categories <ChevronDown size={12} /></button><span className="nav-divider" />{['Fruits & Vegetables', 'Electronics', 'Daily Essentials', 'Beauty & Care', 'Home & Kitchen'].map(name => <button key={name} className={cn(category === name && 'active')} onClick={() => shop(name)}>{name === 'Fruits & Vegetables' ? 'Groceries' : name}</button>)}<button className="nav-deals" onClick={() => { shop('All'); setDealsOnly(true) }}><Tag size={15} /> Today&apos;s deals</button><button className="nav-help" onClick={() => setPanel('help')}><Sparkles size={15} /> Ask Daily</button></div></nav>
    <main className="page-container"><Hero onShop={shop} /><Categories selected={category} onSelect={shop} /><section className="products-section" id="products" aria-labelledby="products-heading"><div className="section-heading"><div><div className="heading-with-label"><h2 id="products-heading">{savedOnly ? 'Your little favourites' : query ? `Results for “${query}”` : category !== 'All' ? category : dealsOnly ? 'Good finds. Better prices.' : 'Your everyday favourites'}</h2>{!savedOnly && !query && category === 'All' && <span className="popular-label">POPULAR PICKS</span>}</div><p>{savedOnly ? 'All the things you love, in one place.' : 'The things you love, at prices you’ll love even more.'}</p></div><label className="sort-control"><SlidersHorizontal size={14} /><select value={sort} onChange={e => setSort(e.target.value)} aria-label="Sort products"><option value="recommended">Recommended</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="rating">Top rated</option></select><ChevronDown size={12} /></label></div><div className="product-filters" aria-label="Filter products">{['All', ...categories.map(c => c.name)].map(name => <button className={cn('filter-chip', category === name && 'active')} key={name} onClick={() => { setCategory(name); setSavedOnly(false); setDealsOnly(false) }} aria-pressed={category === name}>{name === 'All' ? 'All favourites' : name === 'Fruits & Vegetables' ? 'Fresh groceries' : name}</button>)}</div>{filtered.length ? <div className="product-grid">{filtered.map(product => <ProductCard key={product.id} product={product} quantity={cart[product.id] || 0} saved={saved.includes(product.id)} onAdd={() => update(product.id, 1)} onRemove={() => update(product.id, -1)} onSave={() => setSaved(current => current.includes(product.id) ? current.filter(id => id !== product.id) : [...current, product.id])} onView={() => { setViewed(product); setPanel('product') }} />)}</div> : <div className="empty-state"><Search size={32} /><h3>{savedOnly ? 'Your favourites are waiting to be found.' : 'No little finds just yet.'}</h3><p>{savedOnly ? 'Tap the heart on a product to save it for this visit.' : 'Try a different search or explore another category.'}</p><button className="primary-button" onClick={() => shop('All')}>Explore all products <ArrowRight size={15} /></button></div>}<p className="catalog-note">A curated demo collection · Illustrative photos, ratings and prices</p></section><BottomSections onShop={shop} onHelp={() => setPanel('help')} /></main>
    <button className="floating-help" aria-label="Ask Daily shopping assistant" onClick={() => setPanel('help')}><span><Sparkles size={20} /></span><div><strong>A little help?</strong><small>Ask your Daily assistant</small></div><span className="online-dot" /></button>
    {notice && <div className="cart-notice" role="status"><Check size={16} /><span>{notice}</span><button onClick={() => { setNotice(''); setPanel('cart') }}>View bag {money(total)}</button><button aria-label="Dismiss notification" onClick={() => setNotice('')}><X size={15} /></button></div>}
    <StoreModal open={panel !== null} close={() => setPanel(null)} title={title} wide={panel === 'cart'}>{panel === 'cart' && <CartPanel cart={cart} update={update} address={address} close={() => setPanel(null)} editAddress={() => { setAddressReturn('cart'); setPanel('address') }} />}{panel === 'address' && <AddressPanel addresses={addresses} selected={addressIndex} onSelect={index => { setAddressIndex(index); setPanel(addressReturn) }} onAdd={newAddress => { setAddresses(current => [...current, newAddress]); setAddressIndex(addresses.length); setPanel(addressReturn) }} />}{panel === 'help' && <HelpPanel onCategory={shop} />}{panel === 'account' && <AccountPanel />}{panel === 'product' && viewed && <ProductDetail product={viewed} onAdd={() => update(viewed.id, 1)} />}</StoreModal>
  </div>
}
